apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::250416891737:server-certificate/Runeffective"
    route53: '{
                 "qa": {
                        "stable-qa": "api-stable-qa.runeffective.com."},
                 "prod": {
                          "default": "api.runeffective.com"}
                }'
  labels:
    app: conatiner101
    tier: backend
  name: conatiner101
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    name: container101
  sessionAffinity: None
  type: LoadBalancer

