---
   apiVersion: "extensions/v1beta1"
   kind: "Deployment"
   metadata:
     name: "queue"
   spec:
     replicas: 1
     template:
       metadata:
         name: "athena"
         labels:
           tier: "backend"
           name: "queue"
           app: "rails"
       spec:
         containers:
           - name: "rails"
             image: runeffective/athena:$VERSION
             ports:
               - name: "rails-port"
                 containerPort: 3000
             env:
               - name: "RAILS_RESQUE_REDIS"
                 valueFrom:
                   configMapKeyRef:
                     name: default-app
                     key: redis.url
               - name: "REDIS_URL"
                 valueFrom:
                   configMapKeyRef:
                     name: default-app
                     key: redis.url
               - name: "RAILS_ENV"
                 valueFrom:
                   configMapKeyRef:
                     name: default-app
                     key: rails.env
             command: 
               - "bin/worker"
             volumeMounts:
               - name: "secrets"
                 mountPath: "/tmp/secrets/"
               - name: "default-app-vol"
                 mountPath: "/tmp/config/"
         imagePullSecrets:
           - name: "docker-reg"
         volumes:
           - name: "secrets"
             secret:
               secretName: "athena"
           - name: default-app-vol
             configMap:
              name: default-app
              items:
               - key: appconfig
                 path: appconfig


